version: '3.9'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-eh*@r_u7hy$$&fk+bpj$$q8vj0zcxko=@=c^-7@s6xrq)i9a7o65"
      - "DJANGO_DEBUG=True"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: